const uzUZ = {
  "first_player_name" : "Birinchi ishtirokchi ismingizni kiriting: ",
  "second_player_name" : "Ikkinchi ishtirokchi ismini kiriting: ",
  "game_over" : "O'yin tugashi uchun shohga hujum qilish kerak!",
  "the_game_begins" : "O'yin boshlanmoqda",
  "it's_your_turn" : "sizning navbatingiz!",
  "figure_is_located" : "Figurangiz turgan katakni manzilini kiriting: ",
  "entered_an_error" : "xato katak kiritdingiz!",
  'want_to_walk': "yurishi kerak bo'lgan manzilni kiriting: ",
  "can't_walk" : "bilan bunday yurish qila olmaysiz ❌",
  "we" : "Siz",
  "congratulations" : "Tabriklaymiz",
  "won" : "G'olib bo'ldingiz!!!",
  "the_end" : "O'yin tugadi!!!",
  "<= Chess_app =>" : "Shaxmat dasturi",
  "Theme_Select" : " Mavzu Tanlang",
  "Enter_the_Command" : " Buyruq Kiriting ",
  "Subject_changed_success" : " Mavzu muvaffaqiyatli o'zgartirildi ",
  "Manage_Saved_Games" : " Saqlangan o'yinlarni boshqarish ",
  "No_Saved_Games" : " Hozircha saqlangan o`yinlar mavjud emas! ",
  "Back_go_enter" : " Ortga qaytish uchun enterni bosing. ",
  "Saved_Games" : " Saqlangan o`yinlar ro`yxati: ",
  "Deleted" : " O'chirish ",
  "Deleted_them" : " Barchasini O'chirish ",
  "Go_Back" : "Ortga Qaytish ",
  "Return_Main_Menu" : " Bosh Menyuga Qaytish ",
  "Game_Number" : " O`yin raqamini kiriting: ",
  "Successfully_Deleted!" : " Muvofaqqiyatli o`chirildi! ",
  "Wrong_Name_Entered !!" : " Noto`g`ri nom kiritildi!! ",
  "All_games_successfully_deleted!" : " Barcha o`yinlar muvofaqqiyatli o`chirildi! ",
  "Wrong_Command_Entered!" : "Noto`g`ri buyruq kiritildi!",
  "SETTINGS" : "Sozlamalar",
  "Language_Change:" : " Tilni o`zgartirish: ",
  "Theme_Update:" : " Mavzuni o`zgartirish: ",
  "Change_Name" : " Ismni O'zgartirish ",
  "Start_Game" : " O`yinni boshlash ",
  "Play_Pairs" : " Ikki nafar bo`lib o`ynash ",
  "Play_The_Another_Device" : " Boshqa qurilma bilan bog`lanib o`ynash ",
  "Enter_the_name_of_another_device_player:": 'boshqa qurilma o`yinchisi ismini kiriting: ',
  'Select_White_or_Black:': ' Oq yoki Qora rangni tanlang(Oq = true / Qora = false): ',
  'Enter_Exit_to_finish_the_game!': ' O`yinni tugatish uchun Exit`ni kiriting!',
  'Game_over!': ' O`yin tugatildi!',
  'is_waiting_for': 'ning navbati kutilmoqda...',
  'finished_the_game': ' o`yinni yakunladi!',
  'Press_enter_to_go_back:': ' Ortga qaytish uchun enterni bosing: ',
  'you_were_given_a_horn': ' sizga shox berildi!',
  'Play': 'O`ynash',
  'Exit_the_application': 'Ilovadan chiqish',
  'Enter_the_command:': 'Buyruqni kiriting: ',
  'Select_the_program_language:': ' Dastur tilini tanlang: ',
  'Program_language_successfully_changed!': ' Dastur tili muvaffaqiyatli o`zgartirildi!',
  'Manage_saved_games': 'Saqlangan o`yinlarni boshqarish',





};